language: php
php:
  - '7.1'

script:
   - composer install
   - php bin/console doctrine:create:database --env=test
   - php bin/console doctrine:schema:update --force --env=test
   - vendor/bin/phpunit